<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class ModeloSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('modelos')->insert(['nombre' => 'INTEGRA','marca_id'=>1,]);
        DB::table('modelos')->insert(['nombre' => 'LEGEND','marca_id'=>1,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>1,]);
        DB::table('modelos')->insert(['nombre' => '146','marca_id'=>2,]);
        DB::table('modelos')->insert(['nombre' => '156','marca_id'=>2,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>2,]);
        DB::table('modelos')->insert(['nombre' => 'VANTAGE','marca_id'=>3,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>3,]);
        DB::table('modelos')->insert(['nombre' => '90','marca_id'=>4,]);
        DB::table('modelos')->insert(['nombre' => 'A3','marca_id'=>4,]);
        DB::table('modelos')->insert(['nombre' => 'A4','marca_id'=>4,]);
        DB::table('modelos')->insert(['nombre' => 'A5','marca_id'=>4,]);
        DB::table('modelos')->insert(['nombre' => 'A6','marca_id'=>4,]);
        DB::table('modelos')->insert(['nombre' => 'A8','marca_id'=>4,]);
        DB::table('modelos')->insert(['nombre' => 'Q7','marca_id'=>4,]);
        DB::table('modelos')->insert(['nombre' => 'S4','marca_id'=>4,]);
        DB::table('modelos')->insert(['nombre' => 'TT','marca_id'=>4,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>4,]);
        DB::table('modelos')->insert(['nombre' => 'SERIE 1','marca_id'=>5,]);
        DB::table('modelos')->insert(['nombre' => 'SERIE 3','marca_id'=>5,]);
        DB::table('modelos')->insert(['nombre' => 'SERIE 5','marca_id'=>5,]);
        DB::table('modelos')->insert(['nombre' => 'SERIE 6','marca_id'=>5,]);
        DB::table('modelos')->insert(['nombre' => 'SERIE 7','marca_id'=>5,]);
        DB::table('modelos')->insert(['nombre' => 'SERIE 8','marca_id'=>5,]);
        DB::table('modelos')->insert(['nombre' => 'X3','marca_id'=>5,]);
        DB::table('modelos')->insert(['nombre' => 'X5','marca_id'=>5,]);
        DB::table('modelos')->insert(['nombre' => 'X6','marca_id'=>5,]);
        DB::table('modelos')->insert(['nombre' => 'Z3','marca_id'=>5,]);
        DB::table('modelos')->insert(['nombre' => 'Z4','marca_id'=>5,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>5,]);
        DB::table('modelos')->insert(['nombre' => 'F3','marca_id'=>6,]);
        DB::table('modelos')->insert(['nombre' => 'FLYER','marca_id'=>6,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>6,]);
        DB::table('modelos')->insert(['nombre' => 'CENTURY','marca_id'=>7,]);
        DB::table('modelos')->insert(['nombre' => 'LE SABRE','marca_id'=>7,]);
        DB::table('modelos')->insert(['nombre' => 'RIVIERA','marca_id'=>7,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>7,]);
        DB::table('modelos')->insert(['nombre' => 'DEVILLE','marca_id'=>8,]);
        DB::table('modelos')->insert(['nombre' => 'ESCALADE','marca_id'=>8,]);
        DB::table('modelos')->insert(['nombre' => 'FLEETWOOD','marca_id'=>8,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>8,]);
        DB::table('modelos')->insert(['nombre' => 'BENNI','marca_id'=>9,]);
        DB::table('modelos')->insert(['nombre' => 'MINI PICK UP','marca_id'=>9,]);
        DB::table('modelos')->insert(['nombre' => 'PICK - UP','marca_id'=>9,]);
        DB::table('modelos')->insert(['nombre' => 'SUPER VAN','marca_id'=>9,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>9,]);
        DB::table('modelos')->insert(['nombre' => 'IDEAL','marca_id'=>10,]);
        DB::table('modelos')->insert(['nombre' => 'PICK UP','marca_id'=>10,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>10,]);
        DB::table('modelos')->insert(['nombre' => 'COWIN','marca_id'=>11,]);
        DB::table('modelos')->insert(['nombre' => 'QQ','marca_id'=>11,]);
        DB::table('modelos')->insert(['nombre' => 'TIGGO','marca_id'=>11,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>11,]);
        DB::table('modelos')->insert(['nombre' => 'ASTRA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'AVALANCHE','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'AVEO','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'BLAZER','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'C-10','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'C-20','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'C-30','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'CAMARO','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'CAMINO','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'CAPRICE','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'CAPTIVA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'CAVALIER','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'CELEBRITY','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'CENTURY','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'CHEVETTE','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'CHEVY C2','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'CHEYENNE','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'COLORADO','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'CORSA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'CORSICA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'CORVETTE','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'CRUZE','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'EPICA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'ESTEEM','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'EXPEDITION','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'GEO TRACKER','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'GRAND BLAZER','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'GRAND VITARA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'IMPALA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'JIMNY','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'LUMINA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'LUV','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'MALIBU','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'MERIVA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'MONTANA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'MONTE CARLO','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'MONZA ','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'NOVA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'OPTRA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'PICK - UP','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'RANCHERO','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'S-10','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'SIERRA ','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'SILVERADO','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'SPARK','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'SUBURBAN','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'SURFIRE','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'SUPER CARRY','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'SWIFT','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'TAHOE','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'TRAILBLAZER','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'VAN','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'VECTRA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'VENTURE','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'VITARA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'WAGON R','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'YUCON','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>12,]);
        DB::table('modelos')->insert(['nombre' => '300 C','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'BRISA','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'CALIBER','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'CHARGER','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'CORONET','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'GRAN CARAVAN','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'INTREPID','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'LE BARON','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'NEON','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'NEW YORKER','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'PT CRUISER','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'RAM PICK - UP','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'RAM VAN','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'SEBRING','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'SPIRIT','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'STRATUS','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'TOWN & COUNTRY','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>13,]);
        DB::table('modelos')->insert(['nombre' => 'BERLINGO','marca_id'=>14,]);
        DB::table('modelos')->insert(['nombre' => 'C2','marca_id'=>14,]);
        DB::table('modelos')->insert(['nombre' => 'C3','marca_id'=>14,]);
        DB::table('modelos')->insert(['nombre' => 'C4','marca_id'=>14,]);
        DB::table('modelos')->insert(['nombre' => 'JUMPY','marca_id'=>14,]);
        DB::table('modelos')->insert(['nombre' => 'XSARA','marca_id'=>14,]);
        DB::table('modelos')->insert(['nombre' => 'XSARA PICASSO','marca_id'=>14,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>14,]);
        DB::table('modelos')->insert(['nombre' => 'CORVETTE','marca_id'=>15,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>15,]);
        DB::table('modelos')->insert(['nombre' => 'CHAIRMAN','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'CIELO','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'DAMAS','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'ESPERO','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'LOBO','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'LANOS','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'LEGANZA','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'LUBLIN','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'MATIZ','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'MUSSO','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'NUBIRA','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'PRINCE','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'RACER','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'SUPER SALOON','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'TACUMA','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'TICO','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>16,]);
        DB::table('modelos')->insert(['nombre' => 'BRISA','marca_id'=>17,]);
        DB::table('modelos')->insert(['nombre' => 'CALIBER','marca_id'=>17,]);
        DB::table('modelos')->insert(['nombre' => 'CARAVAN','marca_id'=>17,]);
        DB::table('modelos')->insert(['nombre' => 'CHARGER','marca_id'=>17,]);
        DB::table('modelos')->insert(['nombre' => 'DAKOTA','marca_id'=>17,]);
        DB::table('modelos')->insert(['nombre' => 'DART','marca_id'=>17,]);
        DB::table('modelos')->insert(['nombre' => 'INTREPID','marca_id'=>17,]);
        DB::table('modelos')->insert(['nombre' => 'JOURNEY','marca_id'=>17,]);
        DB::table('modelos')->insert(['nombre' => 'NEON','marca_id'=>17,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>17,]);
        DB::table('modelos')->insert(['nombre' => 'FERRARI','marca_id'=>18,]);
        DB::table('modelos')->insert(['nombre' => '147','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'ADVENTURE','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'BRAVA','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'COUPE','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'CROMA','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'DUCATO','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'FIORINO','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'IDEA ','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'MAREA','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'MIRAFIORI','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'PALIO','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'PREMIO','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'PUNTO','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'RAGATTA','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'RITMO','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'SIENA','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'SPAZIO','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'STILO','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'STRADA','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'TEMPRA','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'TIPO','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'TUCAN ','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'UNO','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>19,]);
        DB::table('modelos')->insert(['nombre' => 'BRONCO','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'CLUB WAGON','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'COBRA','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'CONQUISTADOR','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'CORCEL','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'COUGAR','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'CROWN VICTORIA','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'DEL REY','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'ECOSPORT','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'ECONOLINE','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'ESCAPE','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'ESCORT','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'EXCURSION','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'EXPEDITON','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'EXPLORER','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'F-100','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'F-150','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'F-250','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'F-350','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'F-750','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'FAIRLANE','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'FAIRMONT','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'FESTIVA','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'FIESTA','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'FOCUS','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'FORTALEZA','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'FUSION','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'GALAXIE','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'GRANADA','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'GRAND MARQUIS','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'KA','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'LTD','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'LASER','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'MAVERICK','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'MUSTANG','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'PROBE','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'RANCHERA','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'RANGER','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'PICK - UP','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'SIERRA','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'SPORT TRAC','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'SPORT WAGON','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'TAURUS','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'THUNDERBIRD','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'WINDSTART','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'ZEPHYR','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>20,]);
        DB::table('modelos')->insert(['nombre' => 'CK','marca_id'=>21,]);
        DB::table('modelos')->insert(['nombre' => 'HA','marca_id'=>21,]);
        DB::table('modelos')->insert(['nombre' => 'MK','marca_id'=>21,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>21,]);
        DB::table('modelos')->insert(['nombre' => 'DEER','marca_id'=>22,]);
        DB::table('modelos')->insert(['nombre' => 'HOVER','marca_id'=>22,]);
        DB::table('modelos')->insert(['nombre' => 'SAFE','marca_id'=>22,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>22,]);
        DB::table('modelos')->insert(['nombre' => 'LOBO','marca_id'=>23,]);
        DB::table('modelos')->insert(['nombre' => 'MINI VAN','marca_id'=>23,]);
        DB::table('modelos')->insert(['nombre' => 'SUPER MINYI','marca_id'=>23,]);
        DB::table('modelos')->insert(['nombre' => 'ZHONGYI','marca_id'=>23,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>23,]);
        DB::table('modelos')->insert(['nombre' => 'FAMILY','marca_id'=>24,]);
        DB::table('modelos')->insert(['nombre' => 'FREEMA','marca_id'=>24,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>24,]);
        DB::table('modelos')->insert(['nombre' => 'ACCORD','marca_id'=>25,]);
        DB::table('modelos')->insert(['nombre' => 'CR-V','marca_id'=>25,]);
        DB::table('modelos')->insert(['nombre' => 'CRX','marca_id'=>25,]);
        DB::table('modelos')->insert(['nombre' => 'CIVIC','marca_id'=>25,]);
        DB::table('modelos')->insert(['nombre' => 'FIT','marca_id'=>25,]);
        DB::table('modelos')->insert(['nombre' => 'INTEGRA','marca_id'=>25,]);
        DB::table('modelos')->insert(['nombre' => 'LEGEND','marca_id'=>25,]);
        DB::table('modelos')->insert(['nombre' => 'ODYSSEY','marca_id'=>25,]);
        DB::table('modelos')->insert(['nombre' => 'PILOT','marca_id'=>25,]);
        DB::table('modelos')->insert(['nombre' => 'PRELUDE','marca_id'=>25,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>25,]);
        DB::table('modelos')->insert(['nombre' => 'H2','marca_id'=>26,]);
        DB::table('modelos')->insert(['nombre' => 'H3','marca_id'=>26,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>26,]);
        DB::table('modelos')->insert(['nombre' => 'ACCENT','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'ATOS','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'AZERA','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'ELANTRA','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'EXCEL','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'GALLOPER','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'GETZ','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'GRACE','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'H1','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'H10','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'H100','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'MATRIX','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'SANTA FE','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'SANTAMO','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'SCOUPE','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'SONATA','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'TIBURON','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'TUCSON','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'VERACRUZ','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'VERNA','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>27,]);
        DB::table('modelos')->insert(['nombre' => 'INFINITI','marca_id'=>28,]);
        DB::table('modelos')->insert(['nombre' => 'AMIGO','marca_id'=>29,]);
        DB::table('modelos')->insert(['nombre' => 'CARIBE','marca_id'=>29,]);
        DB::table('modelos')->insert(['nombre' => 'RODEO','marca_id'=>29,]);
        DB::table('modelos')->insert(['nombre' => 'TROOPER','marca_id'=>29,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>29,]);
        DB::table('modelos')->insert(['nombre' => 'PICK - UP','marca_id'=>30,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>30,]);
        DB::table('modelos')->insert(['nombre' => 'S - TYPE ','marca_id'=>31,]);
        DB::table('modelos')->insert(['nombre' => 'XJ','marca_id'=>31,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>31,]);
        DB::table('modelos')->insert(['nombre' => 'CJ','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'CHEROKEE','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'COMANCHE','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'COMMANDER','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'COMPASS','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'GRAND CHEROKEE','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'LLANERO ','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'PICK - UP','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'RENEGADO','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'RUBICON','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'SAHARA','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'WAGONEER','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'WILLYS','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'WRANGLER','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>32,]);
        DB::table('modelos')->insert(['nombre' => 'CARENS','marca_id'=>33,]);
        DB::table('modelos')->insert(['nombre' => 'CARNIVAL','marca_id'=>33,]);
        DB::table('modelos')->insert(['nombre' => 'CERATO','marca_id'=>33,]);
        DB::table('modelos')->insert(['nombre' => 'OPIRUS','marca_id'=>33,]);
        DB::table('modelos')->insert(['nombre' => 'OPTIMA','marca_id'=>33,]);
        DB::table('modelos')->insert(['nombre' => 'PICANTO','marca_id'=>33,]);
        DB::table('modelos')->insert(['nombre' => 'PREGIO','marca_id'=>33,]);
        DB::table('modelos')->insert(['nombre' => 'RIO','marca_id'=>33,]);
        DB::table('modelos')->insert(['nombre' => 'SEDONA','marca_id'=>33,]);
        DB::table('modelos')->insert(['nombre' => 'SHUMA','marca_id'=>33,]);
        DB::table('modelos')->insert(['nombre' => 'SORENTO','marca_id'=>33,]);
        DB::table('modelos')->insert(['nombre' => 'SPECTRA','marca_id'=>33,]);
        DB::table('modelos')->insert(['nombre' => 'SPORTAGE','marca_id'=>33,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>33,]);
        DB::table('modelos')->insert(['nombre' => '21053','marca_id'=>34,]);
        DB::table('modelos')->insert(['nombre' => '2106','marca_id'=>34,]);
        DB::table('modelos')->insert(['nombre' => '2107','marca_id'=>34,]);
        DB::table('modelos')->insert(['nombre' => 'ACUARIO','marca_id'=>34,]);
        DB::table('modelos')->insert(['nombre' => 'MATRISKA','marca_id'=>34,]);
        DB::table('modelos')->insert(['nombre' => 'NIVA','marca_id'=>34,]);
        DB::table('modelos')->insert(['nombre' => 'SAMARA','marca_id'=>34,]);
        DB::table('modelos')->insert(['nombre' => 'STRADA','marca_id'=>34,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>34,]);
        DB::table('modelos')->insert(['nombre' => 'DEFENDER','marca_id'=>35,]);
        DB::table('modelos')->insert(['nombre' => 'DISCOVERY','marca_id'=>35,]);
        DB::table('modelos')->insert(['nombre' => 'FREELANDER','marca_id'=>35,]);
        DB::table('modelos')->insert(['nombre' => 'RANGE ROVER','marca_id'=>35,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>35,]);
        DB::table('modelos')->insert(['nombre' => 'ES','marca_id'=>36,]);
        DB::table('modelos')->insert(['nombre' => 'GS','marca_id'=>36,]);
        DB::table('modelos')->insert(['nombre' => 'GX','marca_id'=>36,]);
        DB::table('modelos')->insert(['nombre' => 'IS','marca_id'=>36,]);
        DB::table('modelos')->insert(['nombre' => 'LS','marca_id'=>36,]);
        DB::table('modelos')->insert(['nombre' => 'LX','marca_id'=>36,]);
        DB::table('modelos')->insert(['nombre' => 'RX','marca_id'=>36,]);
        DB::table('modelos')->insert(['nombre' => 'SC ','marca_id'=>36,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>36,]);
        DB::table('modelos')->insert(['nombre' => '520','marca_id'=>37,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>37,]);
        DB::table('modelos')->insert(['nombre' => 'NAVIGATOR','marca_id'=>38,]);
        DB::table('modelos')->insert(['nombre' => 'TOWN CAR','marca_id'=>38,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>38,]);
        DB::table('modelos')->insert(['nombre' => '228','marca_id'=>39,]);
        DB::table('modelos')->insert(['nombre' => '70','marca_id'=>39,]);
        DB::table('modelos')->insert(['nombre' => 'GRAN TURISMO','marca_id'=>39,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>39,]);
        DB::table('modelos')->insert(['nombre' => '2','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => '323','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => '626','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => '929','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'ALLEGRO','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'B-2600','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'B-4000','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'BT-50','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'CX-7','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'CX-9','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'DEMIO','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'MPV','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'MX3','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'MX6','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'MAZDA 3','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'MAZDA 5','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'MAZDA 6','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'MIATA','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'MILLENIA','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'NAVAJO','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'PROTEGE','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'RX-7','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'RX-8','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'TRIBUTE','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>40,]);
        DB::table('modelos')->insert(['nombre' => 'CLASE A','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'CLASE B','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'CLASE C','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'CLASE CL','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'CLASE CLK','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'CLASE CLS','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'CLASE E','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'CLASE G','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'CLASE M ','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'CLASE S','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'CLASE SL','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'CLASE SLC','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'CLASE SLK','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'MB','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'ML','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'SMART','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'SPRINTER','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>41,]);
        DB::table('modelos')->insert(['nombre' => 'COUGAR ','marca_id'=>42,]);
        DB::table('modelos')->insert(['nombre' => 'GRAD MARQUIS','marca_id'=>42,]);
        DB::table('modelos')->insert(['nombre' => 'TRACER','marca_id'=>42,]);
        DB::table('modelos')->insert(['nombre' => 'VILLAGER','marca_id'=>42,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>42,]);
        DB::table('modelos')->insert(['nombre' => 'COOPER','marca_id'=>43,]);
        DB::table('modelos')->insert(['nombre' => 'COOPER S','marca_id'=>43,]);
        DB::table('modelos')->insert(['nombre' => 'CORD ','marca_id'=>43,]);
        DB::table('modelos')->insert(['nombre' => 'JOHN COOPER WORKS','marca_id'=>43,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>43,]);
        DB::table('modelos')->insert(['nombre' => '3000 GT','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'COLT ','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'DIAMANTE','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'ECLIPSE','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'EVOLUTION','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'EXPO','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'GALANT','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'GRANDIS','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'L-200 SPORTERO','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'L-300','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'LANCER','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'MF','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'MS','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'MX','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'MIRAGE','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'MONTERO','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'OUTLANDER','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'PANEL','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'SIGMA','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'SIGNO','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'SPACE WAGON','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'SPORT WAGON','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'STAR WAGON','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'VAN','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>44,]);
        DB::table('modelos')->insert(['nombre' => '200 SX','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => '300 ZX','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => '350Z','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'ALMERA','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'ALTIMA','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'ARMADA','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'FRONTIER','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'LUCINO','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'MAXIMA','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'MURANO','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'PATHFINDER','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'PATROL','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'PRIMERA','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'QUEST','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'SENTRA','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'TERRANO','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'TIIDA','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'TITAN','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'X- TERRA','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'X-TRAIL','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>45,]);
        DB::table('modelos')->insert(['nombre' => '205','marca_id'=>46,]);
        DB::table('modelos')->insert(['nombre' => '206','marca_id'=>46,]);
        DB::table('modelos')->insert(['nombre' => '305','marca_id'=>46,]);
        DB::table('modelos')->insert(['nombre' => '306','marca_id'=>46,]);
        DB::table('modelos')->insert(['nombre' => '307','marca_id'=>46,]);
        DB::table('modelos')->insert(['nombre' => '309','marca_id'=>46,]);
        DB::table('modelos')->insert(['nombre' => '405','marca_id'=>46,]);
        DB::table('modelos')->insert(['nombre' => '407','marca_id'=>46,]);
        DB::table('modelos')->insert(['nombre' => '605','marca_id'=>46,]);
        DB::table('modelos')->insert(['nombre' => '607','marca_id'=>46,]);
        DB::table('modelos')->insert(['nombre' => 'EXPERT','marca_id'=>46,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>46,]);
        DB::table('modelos')->insert(['nombre' => 'FIERO','marca_id'=>47,]);
        DB::table('modelos')->insert(['nombre' => 'FIREBIRD','marca_id'=>47,]);
        DB::table('modelos')->insert(['nombre' => 'GRAND AM','marca_id'=>47,]);
        DB::table('modelos')->insert(['nombre' => 'GRAND PRIX','marca_id'=>47,]);
        DB::table('modelos')->insert(['nombre' => 'SUNFIRE','marca_id'=>47,]);
        DB::table('modelos')->insert(['nombre' => 'TRANS SPORT','marca_id'=>47,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>47,]);
        DB::table('modelos')->insert(['nombre' => '911','marca_id'=>48,]);
        DB::table('modelos')->insert(['nombre' => '924','marca_id'=>48,]);
        DB::table('modelos')->insert(['nombre' => '968','marca_id'=>48,]);
        DB::table('modelos')->insert(['nombre' => 'BOXSTER','marca_id'=>48,]);
        DB::table('modelos')->insert(['nombre' => 'CAYENNE','marca_id'=>48,]);
        DB::table('modelos')->insert(['nombre' => 'CAYMAN','marca_id'=>48,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>48,]);
        DB::table('modelos')->insert(['nombre' => 'CLIO','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'FUEGO','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'GALA','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'KANGOO','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'LAGUNA','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'LOGAN','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'MEGANE','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'R12','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'R11','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'R18','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'R19','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'R21','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'R5','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'SANDERO','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'SCENIC','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'SYMBOL','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'TRAFIC','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'TWINGO','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>49,]);
        DB::table('modelos')->insert(['nombre' => 'MINI VAN','marca_id'=>50,]);
        DB::table('modelos')->insert(['nombre' => 'PANEL','marca_id'=>50,]);
        DB::table('modelos')->insert(['nombre' => 'SUPER VAN','marca_id'=>50,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>50,]);
        DB::table('modelos')->insert(['nombre' => 'TC','marca_id'=>51,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>51,]);
        DB::table('modelos')->insert(['nombre' => 'ALTEA','marca_id'=>52,]);
        DB::table('modelos')->insert(['nombre' => 'CORDOBA','marca_id'=>52,]);
        DB::table('modelos')->insert(['nombre' => 'CUPRA','marca_id'=>52,]);
        DB::table('modelos')->insert(['nombre' => 'IBIZA','marca_id'=>52,]);
        DB::table('modelos')->insert(['nombre' => 'LEON','marca_id'=>52,]);
        DB::table('modelos')->insert(['nombre' => 'TOLEDO','marca_id'=>52,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>52,]);
        DB::table('modelos')->insert(['nombre' => 'FABIA','marca_id'=>53,]);
        DB::table('modelos')->insert(['nombre' => 'FORMAN','marca_id'=>53,]);
        DB::table('modelos')->insert(['nombre' => 'OCTAVIA','marca_id'=>53,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>53,]);
        DB::table('modelos')->insert(['nombre' => 'PASSION','marca_id'=>54,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>54,]);
        DB::table('modelos')->insert(['nombre' => 'FORESTER','marca_id'=>55,]);
        DB::table('modelos')->insert(['nombre' => 'IMPREZA','marca_id'=>55,]);
        DB::table('modelos')->insert(['nombre' => 'LEGACY','marca_id'=>55,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>55,]);
        DB::table('modelos')->insert(['nombre' => 'SUZUKI','marca_id'=>56,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>56,]);
        DB::table('modelos')->insert(['nombre' => 'INDICA','marca_id'=>57,]);
        DB::table('modelos')->insert(['nombre' => 'INDIGA','marca_id'=>57,]);
        DB::table('modelos')->insert(['nombre' => 'INDIGO','marca_id'=>57,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>57,]);
        DB::table('modelos')->insert(['nombre' => '4RUNNER','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'AUTANA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'AVALON','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'AVENSIS','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'BURBUJA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'CAMRY','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'CARINA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'CELICA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'COROLLA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'CRESSIDA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'CROWN ','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'ECHO','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'FJ CRUISER','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'FJ-40','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'FORTUNER','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'HIACE','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'HIGHLANDER','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'HILUX','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'MR2','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'MACHO','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'MACHO PICK - UP','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'MATRIX','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'MERU ','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'PASEO','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'PICNIC','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'PRADO','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'PREVIA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'RAV-4','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'RORAIMA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'SANDERO','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'SAMURAI','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'SEQUOIA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'SIENNA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'SKY','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'SOLARA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'STARLET','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'SUPRA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'TACOMA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'TERCEL','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'TERIOS','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'TUNDRA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'YARIS','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>58,]);
        DB::table('modelos')->insert(['nombre' => 'TYANYE','marca_id'=>59,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>59,]);
        DB::table('modelos')->insert(['nombre' => 'BORA','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'BRASILIA','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'BUGGY','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'CADDY','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'CROSSFOX','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'ESCARABAJO','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'FOX','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'GOL','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'GOLF','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'JETTA','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'KOMBI','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'MULTIVAN','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'NEW BEETLE','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'PARATI','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'PASSAT','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'POLO ','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'POLO CLASIC','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'PUMA','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'SAVEIRO','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'SPACEFOX','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'TOUAREG','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'VENTO','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>60,]);
        DB::table('modelos')->insert(['nombre' => 'ADMIRAL','marca_id'=>61,]);
        DB::table('modelos')->insert(['nombre' => 'GRAND TIGER','marca_id'=>61,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>61,]);
        DB::table('modelos')->insert(['nombre' => 'NOMADA','marca_id'=>62,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>62,]);
        DB::table('modelos')->insert(['nombre' => 'NO APLICA','marca_id'=>63,]);

    }
}
